# Enable plugin debugging (warning: this is very verbose!)
debug: true

# Which worlds are hardcore worlds
worlds:
  hardcore1:
    greeting: "&f[&cHardcore1&f] &cLWC chest protection, no PVP and no raiding"  
  hardcore2:
    greeting: "&f[&cHardcore2&f] &cPVP and raiding are encouraged here!"

# How far away should players be spawned from their previous death point
spawn-distance: 4000

# How long should the player be banned from playing again after death (seconds)
death-ban: 60

# How long to protect the player after they spawn
spawn-protection: 60

# Database settings
mysql:
  host: localhost
  port: 3306
  database: truehardcore
  username: truehardcore
  password: "truehardcore"