# Enable plugin debugging (warning: this is very verbose!)
debug: true

# Which worlds are hardcore worlds
worlds:
  hardcore1:
    greeting: "&f[&cHardcore1&f] &cLWC chest protection, no PVP and no raiding"
    ban-time: 3600
    spawn-distance: 5000
    spawn-protection: 60
  hardcore2:
    greeting: "&f[&cHardcore2&f] &cPVP and raiding are encouraged here!"
    ban-time: 7200
    spawn-distance: 4000
    protection-time: 30

# Database settings
mysql:
  host: localhost
  port: 3306
  database: truehardcore
  username: truehardcore
  password: "truehardcore"