name: TrueHardcore
main: au.com.addstar.truehardcore.TrueHardcore
version: ${project.version}
author: add5tar
softdepend: [Vault, Multiverse-Core, My Worlds, Prism, LWC, VanishNoPacket, WorldBorder, BungeeChatBukkit, Monolith]
description: Multiplayer hardcore plugin to simulate true hardcore

commands:
  truehardcore:
    aliases: th
    description: TrueHardcore command
    
permissions:
  truehardcore.*:
    description: Full access to all commands (admin)
    children:
      truehardcore.use: true
    default: op
  truehardcore.use:
    description: Standard permission for players
  truehardcore.info:
    description: 
  truehardcore.info.other:
    description:
  truehardcore.admin:
    description:
  truehardcore.stats:
    description:
  truehardcore.stats.other:
    description:
  truehardcore.endteleport:
    description: people with this perm can teleport to the end.
