name: TrueHardcore
main: au.com.addstar.truehardcore.TrueHardcore
version: ${project.version}
author: add5tar
softdepend: [Vault, iConomy, Multiverse-Core, My Worlds, WorldEdit, Worldguard, LogBlock]
description: Multiplayer hardcore plugin to simulate true hardcore

commands:
  truehardcore:
    aliases: th
    description: TrueHardcore command
    
permissions:
  truehardcore.*:
    description: Full access to all commands (admin)
    children:
      truehardcore.use: true
    default: op
  truehardcore.use:
    description: Standard permission for players
  truehardcore.info:
    description: 
  truehardcore.info.other:
    description:
  truehardcore.dump:
    description:
  truehardcore.save:
    description:
  