name: TrueHardcore
main: au.com.addstar.truehardcore.TrueHardcore
version: 1.0.1
author: add5tar
softdepend: [Vault, iConomy, Multiverse-Core, My Worlds, WorldEdit, Worldguard]
description: Multiplayer hardcore plugin to simulate true hardcore

commands:
  truehardcore:
    aliases: th
    description: TrueHardcore command 
    
permissions:
  truehardcore.*:
    description: Full access to all commands (admin)
    children:
      truehardcore.use: true
